services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: pass
    ports:
      - 8089:5432
  app:
    image: my_app
    container_name: user_app
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
    ports:
      - 8080:8080
    depends_on:
      - db
